### ISSUE TITLE
Update the roadmap page

### ISSUE THREAD

**Issue by noahpierau** [decred/dcrweb#494]
Update https://decred.org/roadmap/ to move these items forward:

New -> Ongoing
- [ ] Ticket splitting [ongoing](https://twitter.com/decredproject/status/997560763727265792)
- [ ] Decentralized Autonomous Entities [ongoing](https://twitter.com/marco_peereboom/status/1084979310379843584)
- [ ] Decentralized Control of Dev Funds [ongoing](https://twitter.com/marco_peereboom/status/1084979310379843584)

Ongoing -> Completed
- [ ] SPV Wallet Support [done](https://twitter.com/decredproject/status/979414817457844224)
- [ ] Decrediton Politeia Integration [done](https://twitter.com/decredproject/status/1052203697986363392)

There might be items I missed, feel free to add suggestions.

**Comment by Guang168** [comment]
Trezor Decrediton Integration - description says enable storing and sending of Decred using trezor hardware wallet 

It should either be marked done with v1.4.0 release or description should be revised to include voting/staking
