### ISSUE TITLE
Update the roadmap page May 2019

### ISSUE THREAD

**Issue by noahpierau** [decred/dcrweb#660]
Update https://decred.org/roadmap/ to move these items forward:

New -> Ongoing
- [ ] Initial Privacy Release [ongoing](https://twitter.com/BradyDale/status/1128674452978450432)
- [ ] Decrediton Integrations: Lightning Network [ongoing](https://github.com/decred/decrediton/pull/2107)

Ongoing -> Completed
- [ ] Decrediton Integrations: SPV [done](https://github.com/decred/decrediton/issues/1243)
- [ ] Ticket Splitting [done](https://docs.decred.org/proof-of-stake/ticket-splitting/)

There might be items I missed, feel free to add suggestions.
